services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: csharp-api-prod
    ports:
      - "8089:8080"
    restart: always
    volumes:
      # Mounsting the folder where we extracted the files from the busybox
      - ./deploy_temp:/app
    working_dir: /app
    # Now the runtime will find the 'dotnet' command
    entrypoint: ["dotnet", "CsharpAppBuildDocker.Api.dll"]